# apiVersion: v1
# kind: Namespace
# metadata:
#   name: prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: nestjs-container
          image: 192.168.0.212:5555/auth:20231116-041637
          command: ["/bin/bash"]
          args: ["/usr/src/main/entrypoint.sh"]
          # command: ["/bin/sh", "-c"]
          # args: ["./node_modules/.bin/ts-node -P /usr/src/main/tsconfig.json -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:run -d /usr/src/main/dist/data-source.js"]
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: auth-logs
              mountPath: /usr/src/main/logs
          env:
            - name: DATABASE_HOST
              value: "auth-mysql-master-service"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: testtest

        - name: mysql-master-container
          image: 192.168.0.212:5555/mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: testtest
            - name: MYSQL_DATABASE
              value: main
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: auth-mysql-master-data
              mountPath: /var/lib/mysql

        - name: phpmyadmin-container
          image: 192.168.0.212:5555/phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "auth-mysql-master-service" # Use service name for DB host
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: root
            - name: PMA_PASSWORD
              value: testtest

        - name: redis-container
          image: 192.168.0.212:5555/redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: auth-redis-data
              mountPath: /data

        - name: redis-gui-container
          image: 192.168.0.212:5555/rediscommander/redis-commander:latest
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_HOSTS
              value: "auth-redis-service"
            - name: USER
              value: admin
            - name: PASSWORD
              value: testtest

      volumes:
        - name: auth-logs
          persistentVolumeClaim:
            claimName: auth-logs-pvc
          # hostPath:
          #   path: /Users/ijehyeon/server/auth/log
          #   type: DirectoryOrCreate
        - name: auth-mysql-master-data
          persistentVolumeClaim:
            claimName: auth-mysql-master-data-pvc
          # hostPath:
          #   path: /Users/ijehyeon/server/auth/backend/mysql/master
          #   type: DirectoryOrCreate
        - name: auth-redis-data
          persistentVolumeClaim:
            claimName: auth-redis-data-pvc
          # hostPath:
          # path: /Users/ijehyeon/server/auth/backend/redis/data
          # type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-master-service # Service for the mysql-master-container
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: auth-phpmyadmin-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis-gui-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3081
      targetPort: 8081
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-phpmyadmin-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /phpmyadmin-auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-phpmyadmin-service
                port:
                  number: 3080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-redis-gui-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /redis-auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-redis-gui-service
                port:
                  number: 3081
