---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: prod
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: email-mysql-master-service 
  namespace: prod
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: email-phpmyadmin-service
  namespace: prod
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: email-redis-service
  namespace: prod
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: email-redis-gui-service
  namespace: prod
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 3081
      targetPort: 8081
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: email-slave-redis-service
  namespace: prod
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 6380
      targetPort: 6380
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: email-slave-redis-gui-service
  namespace: prod
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 3082
      targetPort: 8082
  type: NodePort