apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: nestjs-container
          image: 192.168.0.212:5555/product:20240321-024928
          command: ["/bin/bash"]
          args: ["/usr/src/main/entrypoint.sh"]
          ports:
            - containerPort: 3005
          volumeMounts:
            - name: product-logs
              mountPath: /usr/src/main/logs
          env:
            - name: DATABASE_HOST
              value: "product-mysql-master-service"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: testtest

        - name: mysql-master-container
          image: 192.168.0.212:5555/mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: testtest
            - name: MYSQL_DATABASE
              value: main
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: product-mysql-master-data
              mountPath: /var/lib/mysql

        - name: phpmyadmin-container
          image: 192.168.0.212:5555/phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "product-mysql-master-service" # Use service name for DB host
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: root
            - name: PMA_PASSWORD
              value: testtest

        - name: redis-container
          image: 192.168.0.212:5555/redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: product-redis-data
              mountPath: /data

        - name: redis-gui-container
          image: 192.168.0.212:5555/rediscommander/redis-commander:latest
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_HOSTS
              value: "product-redis-service"
            - name: USER
              value: admin
            - name: PASSWORD
              value: testtest

        - name: redis-slave-container
          image: 192.168.0.212:5555/redis:latest
          command:
            [
              "redis-server",
              "--port",
              "6380",
              "--slaveof",
              "orchestrator-redis-service",
              "6379",
            ]
          env:
            - name: REDIS_REPLICATION_MODE
              value: "slave"
            - name: REDIS_MASTER_SERVICE
              value: "orchestrator-redis-service"
            - name: REDIS_MASTER_PORT_NUMBER
              value: "6379"
          ports:
            - containerPort: 6380
          volumeMounts:
            - name: product-slave-redis-data
              mountPath: /data

        - name: redis-slave-gui-container
          image: 192.168.0.212:5555/rediscommander/redis-commander:latest
          ports:
            - containerPort: 8082
          env:
            - name: REDIS_HOSTS
              value: "local:localhost:6380"
            - name: PORT
              value: "8082"
            - name: USER
              value: admin
            - name: PASSWORD
              value: testtest

        - name: fluent-bit
          image: 192.168.0.212:5555/fluent/fluent-bit
          volumeMounts:
            - name: product-fluent-config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: product-logs
              mountPath: /usr/src/main/logs

      volumes:
        - name: product-logs
          persistentVolumeClaim:
            claimName: product-logs-pvc
        - name: product-mysql-master-data
          persistentVolumeClaim:
            claimName: product-mysql-master-data-pvc
        - name: product-redis-data
          persistentVolumeClaim:
            claimName: product-redis-data-pvc
        - name: product-slave-redis-data
          persistentVolumeClaim:
            claimName: product-slave-redis-data-pvc
        - name: product-fluent-config
          configMap:
            name: product-fluent-bit-config