---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-master-service # Service for the mysql-master-container
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: auth-phpmyadmin-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis-gui-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3081
      targetPort: 8081
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: auth-slave-redis-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 6380
      targetPort: 6380
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: auth-slave-redis-gui-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3082
      targetPort: 8082
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: auth-fluent-bit-service
  namespace: prod
spec:
  selector:
    app: auth
  ports:
    - name: tcp
      protocol: TCP
      port: 24220
      targetPort: 24224
    - name: udp
      protocol: UDP
      port: 24220
      targetPort: 24224
  type: NodePort