---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /orchestrator(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: orchestrator-service
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator-socket-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/upgrade: "websocket"
    nginx.ingress.kubernetes.io/connection: "upgrade"
    nginx.ingress.kubernetes.io/server-snippets: |
    location / {
      proxysetheader Upgrade $httpupgrade;
      proxyhttpversion 1.1;
      proxysetheader X-Forwarded-Host $httphost;
      proxysetheader X-Forwarded-Proto $scheme;
      proxysetheader X-Forwarded-For $remoteaddr;
      proxysetheader Host $host;
      proxysetheader Connection "upgrade";
      proxycachebypass $httpupgrade;
    }
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /orchestrator-socket(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: orchestrator-socket-service
                port:
                  number: 3100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator-redis-gui-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /redis-orchestrator(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: orchestrator-redis-gui-service
                port:
                  number: 3081