apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: nestjs-container
          image: 192.168.0.212:5555/orchestrator:20231010-233936
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: orchestrator-logs
              mountPath: /usr/src/main/logs
      volumes:
        - name: orchestrator-logs
          hostPath:
            path: /Users/ijehyeon/server/orchestrator/log

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: prod
spec:
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /orchestrator(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: orchestrator-service
                port:
                  number: 3000
