---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: prod
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: user-mysql-master-service 
  namespace: prod
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: user-phpmyadmin-service
  namespace: prod
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: user-redis-service
  namespace: prod
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: user-redis-gui-service
  namespace: prod
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 3081
      targetPort: 8081
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: user-slave-redis-service
  namespace: prod
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 6380
      targetPort: 6380
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: user-slave-redis-gui-service
  namespace: prod
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 3082
      targetPort: 8082
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: user-fluent-bit-service
  namespace: prod
spec:
  selector:
    app: user
  ports:
    - name: tcp
      protocol: TCP
      port: 24220
      targetPort: 24224
    - name: udp
      protocol: UDP
      port: 24220
      targetPort: 24224
  type: NodePort